# fly.toml app configuration file generated for flybondi-fail-sveltekit on 2025-01-01T19:23:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flybondi-fail-sveltekit'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
